# Generated by Django 2.0.6 on 2018-06-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
