# Generated by Django 2.0.6 on 2018-06-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180617_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
