# Generated by Django 2.0.6 on 2018-06-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_case_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
