# Generated by Django 2.0.6 on 2018-06-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180618_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'ACCEPTED'), (2, 'DECLINED')], default=0),
        ),
    ]
