# Generated by Django 2.0.6 on 2018-06-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180618_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not reviewed'), (1, 'Accepted'), (2, 'Declined')], default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='checkpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Checkpoint'),
        ),
    ]
